### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by brulzki** [freenode/web-7.0#333] opened 2017-08-26 02:52 UTC
There's couple of broken links on https://freenode.net/news/nickserv-is-your-friend which both point to http://freenode.net/faq.shtml#nicksetup

I know there's a big warning at the top that the page was imported and links might be broken, but the first line stars with "UPDATE: This is outdated. See here for up-to-date instructions.", and "here" is the first broken link.

There's also a link further down to "optimal configuration" which follows the same url.

I guess the correct best current link for both would be http://freenode.net/kb/answer/registration ??

**Comment by q587p** [comment] 2017-10-24 11:26
After successful registration via NickServ at [Webchat](https://webchat.freenode.net/) I see this message:

> [14:03] -herbert.freenode.net- [freenode-info] why register and identify? your IRC nick is how people know you. http://freenode.net/faq.shtml#nicksetup

Correct link would be http://freenode.net/kb/answer/registration#nickname-setup

**Comment by skullydazed** [comment] 2017-11-13 18:37
I also encountered this when joining a channel set +R:

> [18:27] -ChanServ!ChanServ@services.- [#openmoko] This channel may be set +R which means you *need* to register and identify to nickserv to be able to post. Please read http://freenode.net/faq.shtml#nicksetup for details

**Comment by emersonveenstra** [comment] 2017-11-13 18:47
@skullydazed That is a ChanServ entry message set by the channel ops. You'll need to contact them to have them change it.

**Comment by emersonveenstra** [comment] 2017-11-13 18:49
@q587p This is already known, and a PR has been made here https://github.com/freenode/ircd-seven/pull/113

**Comment by janikrabe** [comment] 2018-01-15 06:05
Pinging @mquin as requested.

**Comment by svbeon** [comment] 2018-01-15 06:51
Duplicate of #186 and #143

**Closed** 2018-01-15 06:51 UTC
