### ISSUE TITLE
Design: Table cells hard to distinguish

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#136] opened 2016-03-23 16:54 UTC
Table cells are hard to distinguish from each other, e.g. on http://freenode.net/support    depending on your text width  (various desktop resolutions tested) the text   "Pentium 4 or better dedicated server 64-bit multi-core" appears to be one flow of text, even though it should be separated  ("Pentium 4 or better" and " dedicated server 64-bit multi-core" being two different items)

Either spacing or lines between table cells (maybe a somewhat lighter grey) should be used.

**Comment by svbeon** [comment] 2016-03-23 16:58
Duplicate of #126

**Closed** 2016-03-24 14:51 UTC
