### ISSUE TITLE
News archive is horribly styled

### ISSUE THREAD

**Issue by edk0** [freenode/web-7.0#137] opened 2016-03-23 16:56 UTC

**Comment by svbeon** [comment] 2016-03-23 16:57
Duplicate of #126

**Comment by svbeon** [comment] 2016-03-24 17:17
The header margins looks horrible on small screens, 
![screenshot_2016-03-24-18-13-33](https://cloud.githubusercontent.com/assets/10356719/14025071/7fef57c8-f1ec-11e5-9086-5f57c44f6c02.png)

**Comment by edk0** [comment] 2016-03-24 17:23
Not related to small screens

**Closed** 2016-03-24 17:45 UTC
