### ISSUE TITLE
Services reporting no-longer-existent URLs

### ISSUE THREAD

**Issue by shadowcat-mst** [freenode/web-7.0#212] opened 2016-05-01 16:21 UTC
e.g. chanserv links you to http://freenode.net/channel_guidelines.shtml

Probably not ideal.

**Comment by shadowcat-mst** [comment] 2016-05-01 16:21
Either chanserv should link http://freenode.net/changuide or you need a redirect.

**Comment by Equinox** [comment] 2016-05-01 19:37
Duplicate of #202.

**Comment by shadowcat-mst** [comment] 2016-05-02 01:37
212 was closed wontfix which is wrong since it's an ongoing problem, if services aren't going to be updated any time soon it should 302; if somebody wants to tell me how the webserver config works I'll try and provide a PR.

**Comment by edk0** [comment] 2016-05-02 02:31
configuring the webserver isn't really an option (and setting redirects per #143 seems to have been vetoed), so i think our only choice here is some services-related prodding.

**Comment by shadowcat-mst** [comment] 2016-05-02 16:27
Apparently needs to be a PR against https://github.com/freenode/atheme-fn - I'll try and get to it at some point if nobody else does.

**Comment by svbeon** [comment] 2016-05-06 16:59
Yeah and that's the exact reason #202 was closed! It has nothing to do with the website.

**Comment by emersonveenstra** [comment] 2016-06-24 00:19
ftr, i opened https://github.com/freenode/atheme-fn/pull/1 for those links.

**Comment by emersonveenstra** [comment] 2016-12-26 21:08
This was done in https://github.com/freenode/atheme-fn/pull/2

**Closed by emersonveenstra** 2016-12-26 21:08 UTC
