### ISSUE TITLE
Text cut off

### ISSUE THREAD

**Issue by LunarTwilight** [freenode/web-7.0#358] opened 2018-03-26 03:24 UTC
When you go the link in topic of #freenode (https://freenode.net/kb/answer/cloaks#cloaks-do-not-effectively-hide-your-ip) the very top of the section gets cut off, as shown.
![image](https://user-images.githubusercontent.com/13520392/37885510-1f13c572-3062-11e8-993d-bac97cb24839.png)

**Comment by equinox** [comment] 2018-03-27 10:16
Duplicate of https://github.com/freenode/web-7.0/issues/200.

In short, this is an unintended result of purposefully not accommodating anchor tags (as the pages were supposed to have sufficiently short content, nobody should need to link to specifics), but as you say, they're now being used by staff themselves.

So potentially worth revisiting the "wontfix" conclusion added to the linked issue above.

**Comment by emersonveenstra** [comment] 2018-03-27 14:52
I would be in favor of getting rid of the sticky header, I don't think it's really necessary to have

**Closed** 2018-05-24 23:49 UTC
Labels: UX, duplicate
