### ISSUE TITLE
Where'd the list of servers go?

### ISSUE THREAD

**Issue by randomdude999** [freenode/web-7.0#219] opened 2016-05-13 14:08 UTC
The old website had a convenient list of servers. I can't find it on the new one.

**Comment by mistohise** [comment] 2016-05-13 14:22
This is intentional to reduce direct linking to servers that may or may not be up at any given point.

**Comment by randomdude999** [comment] 2016-05-13 15:19
But what if I live in Europe and don't want to connect to an American server?

**Comment by svbeon** [comment] 2016-05-14 18:15
Duplicate of #170

**Closed by svbeon** 2016-05-14 18:15 UTC
