### ISSUE TITLE
Broken link in https://freenode.net/news/nickserv-is-your-friend

### ISSUE THREAD

**Issue by hstenn** [freenode/web-7.0#361] opened 2018-05-02 00:51 UTC
The second sentence of the first paragraph of https://freenode.net/news/nickserv-is-your-friend contains a link to: http://freenode.net/faq.shtml#nicksetup

which is no longer valid.

**Comment by svbeon** [comment] 2018-05-02 04:57
Duplicate of #186 and #143 and #333 and #354

**Closed** 2018-05-02 04:58 UTC
Labels: duplicate, wontfix
